name: usa_zipcode_address_finder
description: "Flutter Plugin which retreive latest USA Addresses with Zipcode"
version: 1.0.0
homepage: 

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  http: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0