name: usa_zipcode_address_finder
description: "Flutter plugin to retrieve detailed location information for U.S. zip codes, including address, state, city, local name, area code, and state code. Supports Android and iOS devices"
version: 1.0.0
homepage: 

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  http: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0